// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB51urDGmamvicq1K_Hn-EqM-ydM1O5-jw',
    appId: '1:639859354824:android:c69bfdd8456caa6f64c9fd',
    messagingSenderId: '639859354824',
    projectId: 'caja-arequipa-cliente-aldor',
    storageBucket: 'caja-arequipa-cliente-aldor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_vKo-xb_XSzzjznNHPqY315rKbnjVRG4',
    appId: '1:639859354824:ios:69b33b66d109f76164c9fd',
    messagingSenderId: '639859354824',
    projectId: 'caja-arequipa-cliente-aldor',
    storageBucket: 'caja-arequipa-cliente-aldor.firebasestorage.app',
    iosBundleId: 'com.example.appbancoCajaarequipaFuerzaventas',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAprgJX-bcHrARikcg6I1_JI2uEYB6eYq0',
    appId: '1:639859354824:web:dce344c0ba008f0264c9fd',
    messagingSenderId: '639859354824',
    projectId: 'caja-arequipa-cliente-aldor',
    authDomain: 'caja-arequipa-cliente-aldor.firebaseapp.com',
    storageBucket: 'caja-arequipa-cliente-aldor.firebasestorage.app',
  );
}
